<?php
/** Research-only profiler: refuses any database not marked read-only. No row-level PII output. */
declare(strict_types=1);
$dsn = getenv('MRP_DSN') ?: throw new RuntimeException('MRP_DSN required');
$password = getenv('MRP_PASSWORD') ?: throw new RuntimeException('MRP_PASSWORD required');
$pdo = new PDO($dsn, getenv('MRP_USER') ?: 'SYSDBA', $password, [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]);
function query(string $sql): array {
    global $pdo;
    $rows = $pdo->query($sql)->fetchAll(PDO::FETCH_ASSOC);
    foreach ($rows as &$row) foreach ($row as &$v) if (is_string($v)) $v=trim($v);
    return $rows;
}
function ident(string $s): string { return '"'.str_replace('"','""',$s).'"'; }
$info=query('SELECT MON$ODS_MAJOR AS ODS_MAJOR, MON$ODS_MINOR AS ODS_MINOR, MON$READ_ONLY AS READ_ONLY FROM MON$DATABASE')[0];
if ((int)$info['READ_ONLY'] !== 1) throw new RuntimeException('Refusing to profile writable database');
$out=['captured_at'=>gmdate('c'),'database'=>$info];
$out['tables']=query("SELECT TRIM(RDB\$RELATION_NAME) AS TABLE_NAME FROM RDB\$RELATIONS WHERE COALESCE(RDB\$SYSTEM_FLAG,0)=0 AND RDB\$VIEW_BLR IS NULL ORDER BY RDB\$RELATION_NAME");
$out['columns']=query('SELECT TRIM(r.RDB$RELATION_NAME) AS TABLE_NAME, TRIM(r.RDB$FIELD_NAME) AS COLUMN_NAME, r.RDB$FIELD_POSITION AS COLUMN_POSITION, f.RDB$FIELD_TYPE AS FIELD_TYPE, f.RDB$FIELD_SUB_TYPE AS SUB_TYPE, f.RDB$FIELD_LENGTH AS BYTE_LENGTH, f.RDB$CHARACTER_LENGTH AS TEXT_LENGTH, f.RDB$FIELD_PRECISION AS NUMERIC_PRECISION, f.RDB$FIELD_SCALE AS NUMERIC_SCALE, COALESCE(r.RDB$NULL_FLAG,f.RDB$NULL_FLAG,0) AS NOT_NULL, TRIM(c.RDB$CHARACTER_SET_NAME) AS CHARSET FROM RDB$RELATION_FIELDS r JOIN RDB$FIELDS f ON f.RDB$FIELD_NAME=r.RDB$FIELD_SOURCE JOIN RDB$RELATIONS t ON t.RDB$RELATION_NAME=r.RDB$RELATION_NAME LEFT JOIN RDB$CHARACTER_SETS c ON c.RDB$CHARACTER_SET_ID=f.RDB$CHARACTER_SET_ID WHERE COALESCE(t.RDB$SYSTEM_FLAG,0)=0 ORDER BY r.RDB$RELATION_NAME,r.RDB$FIELD_POSITION');
$out['keys']=query('SELECT TRIM(c.RDB$RELATION_NAME) AS TABLE_NAME, TRIM(c.RDB$CONSTRAINT_NAME) AS CONSTRAINT_NAME, TRIM(c.RDB$CONSTRAINT_TYPE) AS CONSTRAINT_TYPE, TRIM(s.RDB$FIELD_NAME) AS COLUMN_NAME, s.RDB$FIELD_POSITION AS COLUMN_POSITION FROM RDB$RELATION_CONSTRAINTS c LEFT JOIN RDB$INDEX_SEGMENTS s ON s.RDB$INDEX_NAME=c.RDB$INDEX_NAME ORDER BY c.RDB$RELATION_NAME,c.RDB$CONSTRAINT_NAME,s.RDB$FIELD_POSITION');
$out['foreign_keys']=query('SELECT TRIM(c.RDB$RELATION_NAME) AS CHILD_TABLE, TRIM(c.RDB$CONSTRAINT_NAME) AS CONSTRAINT_NAME, TRIM(s.RDB$FIELD_NAME) AS CHILD_COLUMN, TRIM(p.RDB$RELATION_NAME) AS PARENT_TABLE, TRIM(ps.RDB$FIELD_NAME) AS PARENT_COLUMN, s.RDB$FIELD_POSITION AS COLUMN_POSITION, TRIM(r.RDB$UPDATE_RULE) AS UPDATE_RULE, TRIM(r.RDB$DELETE_RULE) AS DELETE_RULE FROM RDB$RELATION_CONSTRAINTS c JOIN RDB$REF_CONSTRAINTS r ON r.RDB$CONSTRAINT_NAME=c.RDB$CONSTRAINT_NAME JOIN RDB$RELATION_CONSTRAINTS p ON p.RDB$CONSTRAINT_NAME=r.RDB$CONST_NAME_UQ JOIN RDB$INDEX_SEGMENTS s ON s.RDB$INDEX_NAME=c.RDB$INDEX_NAME JOIN RDB$INDEX_SEGMENTS ps ON ps.RDB$INDEX_NAME=p.RDB$INDEX_NAME AND ps.RDB$FIELD_POSITION=s.RDB$FIELD_POSITION ORDER BY c.RDB$RELATION_NAME,c.RDB$CONSTRAINT_NAME,s.RDB$FIELD_POSITION');
$out['objects']=query("SELECT 'TRIGGER' AS KIND, TRIM(RDB\$TRIGGER_NAME) AS OBJECT_NAME, TRIM(RDB\$RELATION_NAME) AS TABLE_NAME, RDB\$TRIGGER_INACTIVE AS INACTIVE FROM RDB\$TRIGGERS WHERE COALESCE(RDB\$SYSTEM_FLAG,0)=0 UNION ALL SELECT 'PROCEDURE', TRIM(RDB\$PROCEDURE_NAME), NULL, NULL FROM RDB\$PROCEDURES WHERE COALESCE(RDB\$SYSTEM_FLAG,0)=0 UNION ALL SELECT 'VIEW', TRIM(RDB\$RELATION_NAME), NULL, NULL FROM RDB\$RELATIONS WHERE COALESCE(RDB\$SYSTEM_FLAG,0)=0 AND RDB\$VIEW_BLR IS NOT NULL UNION ALL SELECT 'FUNCTION', TRIM(RDB\$FUNCTION_NAME), NULL, NULL FROM RDB\$FUNCTIONS WHERE COALESCE(RDB\$SYSTEM_FLAG,0)=0");
$dates=[];foreach($out['columns'] as $c) if(in_array((int)$c['FIELD_TYPE'],[12,35],true)) $dates[$c['TABLE_NAME']][]=$c['COLUMN_NAME'];
foreach($out['tables'] as &$t){
    $table=ident($t['TABLE_NAME']);
    $t['ROW_COUNT']=(int)query("SELECT COUNT(*) AS N FROM $table")[0]['N'];
    $t['DATES']=[];
    if($t['ROW_COUNT']>0) foreach($dates[$t['TABLE_NAME']]??[] as $date){
        $col=ident($date);
        $t['DATES'][$date]=query("SELECT COUNT($col) AS NON_NULL, MIN($col) AS MIN_DATE, MAX($col) AS MAX_DATE FROM $table")[0];
    }
}
$out['captured_end']=gmdate('c');
echo json_encode($out, JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR),"\n";
